### ISSUE TITLE
请问能否用于生产环境了？

### ISSUE THREAD

**Issue by my6521** [baihw/flutter_bluetooth_helper#1]

**Comment by baihw** [comment]
谢谢关注！
当前版本还是0.0.x，处在测试探索阶段，只是满足了自己的硬件对接场景，还不够通用。
应该至少要等到0.1.x之后才会相对通用一些，到时变化相对小一些的时候会补充一些详细的使用示例与说明文档的哈。

**Comment by my6521** [comment]
谢谢您的快速回复，我会持续关注。之前一直用flutter开发业务，但没接触过原生开发，这次遇到硬件类的确实对自己是个考验。

**Comment by baihw** [comment]
不客气。刚接触一些陌生的东西，都会有些不适应，做的多了就好了。
你现在急用的话，flutter_blue库挺不错的，可以去看看哈。

**Comment by my6521** [comment]
之前也看了，但从代码结构上来看， 你写的更容易看懂

**Comment by baihw** [comment]
很开心能对你有所帮助，我提交了最新的代码跟仓库的版本同步了，你可以试用看看。有遇到问题的话，只要我知道的，都知无不言哈。

**Comment by my6521** [comment]
好的！有问题再问你

**Comment by baihw** [comment]
好的
